In [ ]:
#import relevant libraries
import torch
import math


print(torch.__version__)

2.13.0+cpu


### Introduction to PyTorch Tensors: from the PyTorch documentation/tutorials

In [5]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
#factory methods to create tensors
zeros = torch.zeros(3,4)        #empty tensor of size 3x4 filled with zeros
print(zeros)
ones = torch.ones(3,4)          #empty tensor of size 3x4 filled with ones
print(ones)

torch.manual_seed(123)  #set the random seed for reproducibility
random = torch.rand(3,4)            #empty tensor of size 3x4 filled with random numbers
print(random)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])


### Random Seeding

In [9]:
torch.manual_seed(1234)             #set the random seed for reproducibility
random1 = torch.rand(3,4)           #demonstrate that the random numbers generated are the same when the seed is set to the same value
print(random1)

random2 = torch.rand(3,4)           #demonstrate that the following rng numbers hold after the reset
print(random2)

torch.manual_seed(1234)
random3 = torch.rand(3,4)           #reproduction of random1
print(random3)

random4 = torch.rand(3,4)           #reproduction of random2
print(random4)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])
tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])


### Tensor Shapes