In [11]:
#import relevant libraries
import torch
import torchvision
import torchaudio
import math


print(torch.__version__)

2.13.0+cu126


## Introduction to PyTorch Tensors: from the PyTorch documentation/tutorials

In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
#factory methods to create tensors
zeros = torch.zeros(3,4)        #empty tensor of size 3x4 filled with zeros
print(zeros)
ones = torch.ones(3,4)          #empty tensor of size 3x4 filled with ones
print(ones)

torch.manual_seed(123)  #set the random seed for reproducibility
random = torch.rand(3,4)            #empty tensor of size 3x4 filled with random numbers
print(random)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])


### Random Seeding

In [4]:
torch.manual_seed(1234)             #set the random seed for reproducibility
random1 = torch.rand(3,4)           #demonstrate that the random numbers generated are the same when the seed is set to the same value
print(random1)

random2 = torch.rand(3,4)           #demonstrate that the following rng numbers hold after the reset
print(random2)

torch.manual_seed(1234)
random3 = torch.rand(3,4)           #reproduction of random1
print(random3)

random4 = torch.rand(3,4)           #reproduction of random2
print(random4)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])
tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])


### Tensor Shapes

In [5]:
x = torch.empty(1,2,3)
print(x.shape)
print(x)


empty_like_x = torch.empty_like(x)  #create an empty tensor with the same shape as x
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([1, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([1, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([1, 2, 3])
tensor([[[0.9665, 0.7399, 0.4517],
         [0.4757, 0.7842, 0.1525]]])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.0
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 6.5959,  6.2865,  3.9558],
        [14.9784, 12.9833,  5.7297]], dtype=torch.float64)
tensor([[ 6,  6,  3],
        [14, 12,  5]], dtype=torch.int32)


### Math and Logic with PyTorch Tensors

Scalar operations and exponentiation act on each element individually.

In [8]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos**2
sqrt2s = twos**0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


When applying BIMDAS operations between two tensors of equal size, each corresponding element interacts with its counterpart and maps into a new tensor of equal dimension.

In [9]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


tensors need to be of equal shape for element wise operations: ie, below fails for this reason

In [12]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [27]:
sequence = torch.arange(1,10,2)
sequence

tensor([1, 3, 5, 7, 9])

### Tensor Broadcasting

The rules for broadcasting are:

1. Each tensor must have at least one dimension - no empty tensors.

2. Comparing the dimension sizes of the two tensors, going from last to first:

3. Each dimension must be equal, or

4. One of the dimensions must be of size 1, or

5. The dimension does not exist in one of the tensors

The smaller tensor is then 

In [13]:
broadtest = torch.ones(1,2,2)
print(broadtest)

tensor([[[1., 1.],
         [1., 1.]]])


Ok so essentially a dimension with extent of 0 must be empty, as actually any non empty tensor has extent of 1 in every dimension, think of it as a 1D vector is a row/column in a matrix, ie. the plane is one point/element in a cube, it possesses existence that can be broadcasted or scaled into any higher dimension, which is what is happening here and why extent of 1 or not named are treated equivalently. Since it isn't defined which row/column the vector is in the dimensional extent, and broadcasting is done equally to each point in the new dim, each 1 is scaled to the larger value, if the no. dimensions don't match, PyTorch adds ones to the left till they do, so you match from the right to left.

In [14]:
twodof = torch.ones(2,3,4)
print(twodof*torch.ones(2,1,1)*2)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


All the max, min, unique elements, matrix multiplication, singular value decomposition, mean, std, etc. operations can be done on tensors with PyTorch torch. methods (torch.linalg.matmul technically for matrix multiplication)

In [15]:
a =torch.ones(1,2,3)
a
b= a*2

In [16]:
a.mul_(2)

tensor([[[2., 2., 2.],
         [2., 2., 2.]]])

In [17]:
b

tensor([[[2., 2., 2.],
         [2., 2., 2.]]])

In [28]:
matrix =  torch.randn(2, 3)
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.numel())
print(matrix.dtype)
print(matrix.device)

tensor([[-0.8147,  0.3559,  0.4221],
        [-0.0466,  0.8169,  0.8579]])
torch.Size([2, 3])
2
6
torch.float32
cpu


In [31]:
import numpy as np

numpy_array = np.array([1.0, 2.0, 3.0])

tensor_from_numpy = torch.from_numpy(numpy_array)
new_numpy_array = tensor_from_numpy.numpy()             #shares memory with the original numpy array, so changes to one will affect the other
independent_tensor = torch.tensor(numpy_array)          #indepedent tensor that does not share memory with the original numpy array, so changes to one will not affect the other

In [29]:
integer_tensor = torch.tensor([1, 2, 3])

float_tensor = integer_tensor.float()
long_tensor = float_tensor.long()
boolean_tensor = integer_tensor.bool()

### Acceleration

In [18]:
if torch.accelerator.is_available():
    print("We have an accelerator!")
else:
    print("Sorry, CPU only.")

We have an accelerator!


In [19]:
import torch

print("PyTorch:", torch.__version__)
print("Built with CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("Device count:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.13.0+cu126
Built with CUDA: 12.6
CUDA available: True
Device count: 1
GPU: NVIDIA GeForce RTX 4090 Laptop GPU


In [25]:
a.type

<function Tensor.type>

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [34]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print("Sorry, CPU only.")

tensor([[0.1272, 0.8167],
        [0.5440, 0.6601]], device='cuda:0')


Tensor computations must all be on the same device, and they're auto created on CPU, so to move them to GPU you need to specify

### Manipulating Tensor Shapes

In [50]:
a = torch.ones(1,2,1,2)
print(a.shape)
b = a.squeeze(-4).shape
print(b)

torch.Size([1, 2, 1, 2])
torch.Size([2, 1, 2])


In [55]:
a = torch.ones(4, 3, 2)
print(a.shape)
b = torch.rand(3)  # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)  # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)  # broadcasting works again!

torch.Size([4, 3, 2])
torch.Size([3, 1])
tensor([[[0.5274, 0.5274],
         [0.6325, 0.6325],
         [0.0910, 0.0910]],

        [[0.5274, 0.5274],
         [0.6325, 0.6325],
         [0.0910, 0.0910]],

        [[0.5274, 0.5274],
         [0.6325, 0.6325],
         [0.0910, 0.0910]],

        [[0.5274, 0.5274],
         [0.6325, 0.6325],
         [0.0910, 0.0910]]])


In [56]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])
